[14:47:01] INFO     initializeDB | Checking for options table,      main.py:368
                    query execute returned <sqlite3.Cursor object              
                    at 0x000002AA89CBEA40>                                     
           INFO     createMediaTable | Creating media table with    main.py:406
                    schema CREATE TABLE IF NOT EXISTS media (id                
                    INTEGER PRIMARY KEY, fileId INTEGER DEFAULT 0,             
                    Count INTEGER DEFAULT 0, destFileName TEXT,                
                    destFilePath TEXT, _Rating INTEGER, _Category              
                    TEXT, _Type TEXT, _Tag TEXT, FileRes TEXT,                 
                    _Deleted BOOLEAN DEFAULT FALSE, _Skipped                   
                    BOOLEAN DEFAULT FALSE, _Processed BOOLEAN                  
                    DEFAULT FALSE, FileSize INTEGER, sourceFilePath            
                    TEXT, soureceFileName TEXT)                                
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN fileId                  
                    INTEGER DEFAULT 0                                          
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN Count                   
                    INTEGER DEFAULT 0                                          
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN destFileName            
                    TEXT                                                       
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN destFilePath            
                    TEXT                                                       
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Rating                 
                    INTEGER                                                    
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Category               
                    TEXT                                                       
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Type TEXT              
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Tag TEXT               
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN FileRes TEXT            
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Deleted                
                    BOOLEAN DEFAULT FALSE                                      
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Skipped                
                    BOOLEAN DEFAULT FALSE                                      
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Processed              
                    BOOLEAN DEFAULT FALSE                                      
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN FileSize                
                    INTEGER                                                    
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN                         
                    sourceFilePath TEXT                                        
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN                         
                    soureceFileName TEXT                                       
           INFO     addColumnsToTable | Adding columns to options   main.py:487
                    table ALTER TABLE media ADD COLUMN _Category               
                    TEXT UNIQUE                                                
           ERROR    addColumnsToTable | Error In addColumnsToTable: main.py:496
           ERROR    log_operational_error | Operational Error: no   main.py:135
                    such table: options                                        
Operational Error: no such table: options
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options
           ERROR    log_exception | SQLite Error occurred: no such  main.py:129
                    table: options                                             
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:494 in addColumnsToTable │            
                    │                                             │            
                    │    491 │   │   │   │   self.error_logger.ha │            
                    │    492 │   │   │   │   continue             │            
                    │    493 │   │   │   try:                     │            
                    │ >  494 │   │   │   │   cursor.execute(f"SEL │            
                    │    495 │   │   │   except Exception as e:   │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: no such table: options                   
SQLite Error: no such table: options
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options
           ERROR    addColumnsToTable | Error adding column         main.py:501
                    _Category                                                  
           ERROR    log_operational_error | Operational Error:      main.py:135
                    duplicate column name: _Category                           
Operational Error: duplicate column name: _Category
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:499 in addColumnsToTable                                 │
│                                                                             │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    498 │   │   │   │   try:                                                 │
│ >  499 │   │   │   │   │   cursor.execute(statement)                        │
│    500 │   │   │   │   except Exception as e:                               │
│    501 │   │   │   │   │   l.error(msg=f"Error adding column {options_colum │
│    502 │   │   │   │   │   self.error_logger.handle_error(error=e)          │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: duplicate column name: _Category
[14:47:02] ERROR    log_exception | SQLite Error occurred:          main.py:129
                    duplicate column name: _Category                           
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:494 in addColumnsToTable │            
                    │                                             │            
                    │    491 │   │   │   │   self.error_logger.ha │            
                    │    492 │   │   │   │   continue             │            
                    │    493 │   │   │   try:                     │            
                    │ >  494 │   │   │   │   cursor.execute(f"SEL │            
                    │    495 │   │   │   except Exception as e:   │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: no such table: options                   
                                                                               
                    During handling of the above exception, another            
                    exception occurred:                                        
                                                                               
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:499 in addColumnsToTable │            
                    │                                             │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    │    498 │   │   │   │   try:                 │            
                    │ >  499 │   │   │   │   │   cursor.execute(s │            
                    │    500 │   │   │   │   except Exception as  │            
                    │    501 │   │   │   │   │   l.error(msg=f"Er │            
                    │    502 │   │   │   │   │   self.error_logge │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: duplicate column name:                   
                    _Category                                                  
SQLite Error: duplicate column name: _Category
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:499 in addColumnsToTable                                 │
│                                                                             │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    498 │   │   │   │   try:                                                 │
│ >  499 │   │   │   │   │   cursor.execute(statement)                        │
│    500 │   │   │   │   except Exception as e:                               │
│    501 │   │   │   │   │   l.error(msg=f"Error adding column {options_colum │
│    502 │   │   │   │   │   self.error_logger.handle_error(error=e)          │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: duplicate column name: _Category
           INFO     addColumnsToTable | Adding columns to options   main.py:487
                    table ALTER TABLE media ADD COLUMN _Type TEXT              
                    UNIQUE                                                     
           ERROR    addColumnsToTable | Error In addColumnsToTable: main.py:496
           ERROR    log_operational_error | Operational Error: no   main.py:135
                    such table: options                                        
Operational Error: no such table: options
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options
           ERROR    log_exception | SQLite Error occurred: no such  main.py:129
                    table: options                                             
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:494 in addColumnsToTable │            
                    │                                             │            
                    │    491 │   │   │   │   self.error_logger.ha │            
                    │    492 │   │   │   │   continue             │            
                    │    493 │   │   │   try:                     │            
                    │ >  494 │   │   │   │   cursor.execute(f"SEL │            
                    │    495 │   │   │   except Exception as e:   │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: no such table: options                   
SQLite Error: no such table: options
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options
           ERROR    addColumnsToTable | Error adding column _Type   main.py:501
           ERROR    log_operational_error | Operational Error:      main.py:135
                    duplicate column name: _Type                               
Operational Error: duplicate column name: _Type
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:499 in addColumnsToTable                                 │
│                                                                             │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    498 │   │   │   │   try:                                                 │
│ >  499 │   │   │   │   │   cursor.execute(statement)                        │
│    500 │   │   │   │   except Exception as e:                               │
│    501 │   │   │   │   │   l.error(msg=f"Error adding column {options_colum │
│    502 │   │   │   │   │   self.error_logger.handle_error(error=e)          │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: duplicate column name: _Type
           ERROR    log_exception | SQLite Error occurred:          main.py:129
                    duplicate column name: _Type                               
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:494 in addColumnsToTable │            
                    │                                             │            
                    │    491 │   │   │   │   self.error_logger.ha │            
                    │    492 │   │   │   │   continue             │            
                    │    493 │   │   │   try:                     │            
                    │ >  494 │   │   │   │   cursor.execute(f"SEL │            
                    │    495 │   │   │   except Exception as e:   │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: no such table: options                   
                                                                               
                    During handling of the above exception, another            
                    exception occurred:                                        
                                                                               
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:499 in addColumnsToTable │            
                    │                                             │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    │    498 │   │   │   │   try:                 │            
                    │ >  499 │   │   │   │   │   cursor.execute(s │            
                    │    500 │   │   │   │   except Exception as  │            
                    │    501 │   │   │   │   │   l.error(msg=f"Er │            
                    │    502 │   │   │   │   │   self.error_logge │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: duplicate column name: _Type             
SQLite Error: duplicate column name: _Type
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:499 in addColumnsToTable                                 │
│                                                                             │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    498 │   │   │   │   try:                                                 │
│ >  499 │   │   │   │   │   cursor.execute(statement)                        │
│    500 │   │   │   │   except Exception as e:                               │
│    501 │   │   │   │   │   l.error(msg=f"Error adding column {options_colum │
│    502 │   │   │   │   │   self.error_logger.handle_error(error=e)          │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: duplicate column name: _Type
           INFO     addColumnsToTable | Adding columns to options   main.py:487
                    table ALTER TABLE media ADD COLUMN _Tag TEXT               
                    UNIQUE                                                     
           ERROR    addColumnsToTable | Error In addColumnsToTable: main.py:496
           ERROR    log_operational_error | Operational Error: no   main.py:135
                    such table: options                                        
Operational Error: no such table: options
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options
           ERROR    log_exception | SQLite Error occurred: no such  main.py:129
                    table: options                                             
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:494 in addColumnsToTable │            
                    │                                             │            
                    │    491 │   │   │   │   self.error_logger.ha │            
                    │    492 │   │   │   │   continue             │            
                    │    493 │   │   │   try:                     │            
                    │ >  494 │   │   │   │   cursor.execute(f"SEL │            
                    │    495 │   │   │   except Exception as e:   │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: no such table: options                   
SQLite Error: no such table: options
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options
           ERROR    addColumnsToTable | Error adding column _Tag    main.py:501
           ERROR    log_operational_error | Operational Error:      main.py:135
                    duplicate column name: _Tag                                
Operational Error: duplicate column name: _Tag
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:499 in addColumnsToTable                                 │
│                                                                             │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    498 │   │   │   │   try:                                                 │
│ >  499 │   │   │   │   │   cursor.execute(statement)                        │
│    500 │   │   │   │   except Exception as e:                               │
│    501 │   │   │   │   │   l.error(msg=f"Error adding column {options_colum │
│    502 │   │   │   │   │   self.error_logger.handle_error(error=e)          │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: duplicate column name: _Tag
           ERROR    log_exception | SQLite Error occurred:          main.py:129
                    duplicate column name: _Tag                                
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:494 in addColumnsToTable │            
                    │                                             │            
                    │    491 │   │   │   │   self.error_logger.ha │            
                    │    492 │   │   │   │   continue             │            
                    │    493 │   │   │   try:                     │            
                    │ >  494 │   │   │   │   cursor.execute(f"SEL │            
                    │    495 │   │   │   except Exception as e:   │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: no such table: options                   
                                                                               
                    During handling of the above exception, another            
                    exception occurred:                                        
                                                                               
                    ┌───── Traceback (most recent call last) ─────┐            
                    │ F:\dler\v2\main.py:499 in addColumnsToTable │            
                    │                                             │            
                    │    496 │   │   │   │   l.error(msg="Error I │            
                    │    497 │   │   │   │   self.error_logger.ha │            
                    │    498 │   │   │   │   try:                 │            
                    │ >  499 │   │   │   │   │   cursor.execute(s │            
                    │    500 │   │   │   │   except Exception as  │            
                    │    501 │   │   │   │   │   l.error(msg=f"Er │            
                    │    502 │   │   │   │   │   self.error_logge │            
                    └─────────────────────────────────────────────┘            
                    OperationalError: duplicate column name: _Tag              
SQLite Error: duplicate column name: _Tag
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:494 in addColumnsToTable                                 │
│                                                                             │
│    491 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    492 │   │   │   │   continue                                             │
│    493 │   │   │   try:                                                     │
│ >  494 │   │   │   │   cursor.execute(f"SELECT {options_column_name} FROM { │
│    495 │   │   │   except Exception as e:                                   │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: no such table: options

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:499 in addColumnsToTable                                 │
│                                                                             │
│    496 │   │   │   │   l.error(msg="Error In addColumnsToTable:")           │
│    497 │   │   │   │   self.error_logger.handle_error(error=e)              │
│    498 │   │   │   │   try:                                                 │
│ >  499 │   │   │   │   │   cursor.execute(statement)                        │
│    500 │   │   │   │   except Exception as e:                               │
│    501 │   │   │   │   │   l.error(msg=f"Error adding column {options_colum │
│    502 │   │   │   │   │   self.error_logger.handle_error(error=e)          │
└─────────────────────────────────────────────────────────────────────────────┘
OperationalError: duplicate column name: _Tag
           ERROR    addColumnsToTable | Not all columns were        main.py:505
                    successfully added                                         
           INFO     initializeDB | Checking for options table,      main.py:377
                    query execute returned <sqlite3.Cursor object              
                    at 0x000002AA89CBEA40>                                     
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN fileId                  
                    INTEGER DEFAULT 0                                          
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN Count                   
                    INTEGER DEFAULT 0                                          
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN destFileName            
                    TEXT                                                       
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN destFilePath            
                    TEXT                                                       
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Rating                 
                    INTEGER                                                    
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Category               
                    TEXT                                                       
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Type TEXT              
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Tag TEXT               
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN FileRes TEXT            
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Deleted                
                    BOOLEAN DEFAULT FALSE                                      
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Skipped                
                    BOOLEAN DEFAULT FALSE                                      
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN _Processed              
                    BOOLEAN DEFAULT FALSE                                      
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN FileSize                
                    INTEGER                                                    
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN                         
                    sourceFilePath TEXT                                        
           INFO     addColumnsToTable | Adding columns to media     main.py:464
                    table ALTER TABLE media ADD COLUMN                         
                    soureceFileName TEXT                                       
           INFO     addColumnsToTable | Adding columns to options   main.py:487
                    table ALTER TABLE media ADD COLUMN _Category               
                    TEXT UNIQUE                                                
           INFO     addColumnsToTable | Adding columns to options   main.py:487
                    table ALTER TABLE media ADD COLUMN _Type TEXT              
                    UNIQUE                                                     
           INFO     addColumnsToTable | Adding columns to options   main.py:487
                    table ALTER TABLE media ADD COLUMN _Tag TEXT               
                    UNIQUE                                                     
           INFO     getQuery_printTable | Executing query: SELECT * main.py:668
                    FROM media                                                 
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬───┬────┬───┐
│ ID │ f… │ C… │ d… │ d… │ _… │ _… │ _… │ _… │ F… │ _… │ _… │ _… │ … │ s… │ … │
├────┼────┼────┼────┼────┼────┼────┼────┼────┼────┼────┼────┼────┼───┼────┼───┤
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴───┴────┴───┘



           INFO     getQuery_printTable | Executing query: SELECT * main.py:710
                    FROM options                                               
┌────┬───────────┬───────┬──────┐
│ ID │ _Category │ _Type │ _Tag │
├────┼───────────┼───────┼──────┤
└────┴───────────┴───────┴──────┘
Application terminated due to an unexpected error: 'str' object has no attribute 'glob'
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\dler\v2\main.py:1023 in main                                             │
│                                                                             │
│   1020 │   │   p.print_exception()                                          │
│   1021 │   │   sys.exit(1)                                                  │
│   1022 │   try:                                                             │
│ > 1023 │   │   startPlayer(db_operations=db_operations, media_ranker=media_ │
│   1024 │   except Exception as e:                                           │
│   1025 │   │   p.print(f"Application terminated due to an unexpected error: │
│   1026 │   │   p.print_exception()                                          │
│                                                                             │
│ F:\dler\v2\main.py:984 in startPlayer                                       │
│                                                                             │
│    981                                                                      │
│    982 def startPlayer(db_operations, media_ranker, db_connection) -> None: │
│    983 │   input_folder: Path = CONFIG["input_folder"]                      │
│ >  984 │   all_files: list[Path] = [f for f in input_folder.glob(pattern="* │
│    985 │   l.info(msg=f"Found {len(all_files)} files in {input_folder}.")   │
│    986 │                                                                    │
│    987 │   if len(all_files) > 0:                                           │
└─────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'str' object has no attribute 'glob'


Goodbye...

